[package]
name = "stack_box"
description = "store unsize struct on stack"
author = ["Fancyflame<fancyflame@163.com>"]
edition = "2021"
license-file = "./LICENSE"
repository = "https://github.com/Fancyflame/stack_box.git"
rust-version = "1.82"
version = "1.0.2"

[dependencies]
thiserror = "2.0"
